// Copyright DYLO Gaming LLC 2026 All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "DCEditorSettings.generated.h"

/**
 * Claude Bridge plugin settings. Visible in Project Settings > Plugins > Claude Bridge.
 */
UCLASS(config = DialogueComponentEditor, defaultconfig, meta = (DisplayName = "Dialogue Component Editor"))
class DIALOGUECOMPONENTEDITOR_API UDCEditorSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	UDCEditorSettings();

	/** Prefix for all comment boxes added to Blueprint graphs. Use this to search/find Claude's changes. */
	UPROPERTY(config, EditAnywhere, Category = "Comments", meta = (DisplayName = "Comment Tag Prefix"))
	FString CommentTagPrefix = TEXT("[CB]");

	/** Color for comment boxes added around Claude's Blueprint changes. */
	UPROPERTY(EditAnywhere, Category = "Comments", meta = (DisplayName = "Comment Color"))
	FLinearColor CommentColor = FLinearColor(0.2f, 0.5f, 1.0f, 1.0f);

	/** PIE window should stay on top of the editor. */
	UPROPERTY(config, EditAnywhere, Category = "Play In Editor", meta = (DisplayName = "PIE Always On Top"))
	bool bPIEAlwaysOnTop = true;

	/** Width of PIE window as percentage of editor window (0.0 - 1.0). */
	UPROPERTY(config, EditAnywhere, Category = "Play In Editor", meta = (DisplayName = "PIE Window Scale", ClampMin = "0.3", ClampMax = "1.0"))
	float PIEWindowScale = 0.7f;

	/** If true, Blueprint graphs generated by Claude will NEVER use custom C++ functions. All nodes will be standard palette nodes only. */
	UPROPERTY(config, EditAnywhere, Category = "Blueprint Generation", meta = (DisplayName = "Standard Nodes Only (No Custom C++)"))
	bool bStandardNodesOnly = true;

	/** Enable verbose logging of all Claude Bridge operations. */
	UPROPERTY(config, EditAnywhere, Category = "Debug", meta = (DisplayName = "Verbose Logging"))
	bool bVerboseLogging = false;

	/** Open the default browser automatically when the bridge server starts. Disable to copy the URL into a different browser yourself. */
	UPROPERTY(config, EditAnywhere, Category = "Toolbar", meta = (DisplayName = "Open Browser After Launch"))
	bool bOpenBrowserAfterLaunch = true;

	/** Editor Utility Widget Blueprint to spawn when the toolbar dropdown's "Launch Editor Utility Widget" entry is clicked. Pick a UEditorUtilityWidgetBlueprint asset from your project. */
	UPROPERTY(config, EditAnywhere, Category = "Toolbar", meta = (DisplayName = "EUW Blueprint", AllowedClasses = "/Script/Blutility.EditorUtilityWidgetBlueprint"))
	FSoftObjectPath EUWBlueprintPath;

	/** When the toolbar button launches the browser editor, also spawn the legacy in-editor EUW alongside. Requires EUW Blueprint to be set above. */
	UPROPERTY(config, EditAnywhere, Category = "Toolbar", meta = (DisplayName = "Also Launch Legacy EUW"))
	bool bAutoLaunchEUW = false;

	// UDeveloperSettings interface
	virtual FName GetContainerName() const override { return TEXT("Project"); }
	virtual FName GetCategoryName() const override { return TEXT("Plugins"); }
	virtual FName GetSectionName() const override { return TEXT("Claude Bridge"); }

#if WITH_EDITOR
	virtual FText GetSectionText() const override { return FText::FromString(TEXT("Claude Bridge")); }
	virtual FText GetSectionDescription() const override { return FText::FromString(TEXT("Settings for the Claude Code bridge plugin.")); }
#endif
};
